# -*- coding: utf-8 -*-
"""7projeto_quiz_neurociencia_web.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1RJJrms3Wvc5bEGpoEDj0n6FnugzAWW9p
"""

import streamlit as st
import random

# --- Estrutura de dados para as perguntas ---
# ********************************************************************************
# *** IMPORTANTE: VOCÊ PRECISA COLAR AQUI TODAS AS 140 PERGUNTAS GERADAS ***
# ********************************************************************************

# CUIDADO: Estas listas serão carregadas e embaralhadas APENAS UMA VEZ
# quando o script é executado pelo Streamlit (na primeira vez ou após uma mudança no código).
# Elas representam o banco completo de perguntas, que será ciclicamente consumido.
all_questions_raw = [
    {
        "category": "Neuroanatomia",
        "question": "O sistema nervoso central (SNC) é composto por quais duas estruturas principais?",
        "options": [
            "Cérebro e nervos cranianos.",
            "Medula espinhal e nervos periféricos.",
            "Encéfalo e medula espinhal.",
            "Sistema nervoso autônomo e sistema nervoso somático."
        ],
        "correct_answer": "Encéfalo e medula espinhal.",
        "explanation": "O SNC é formado pelo encéfalo (cérebro, cerebelo e tronco encefálico) e pela medula espinhal, que processam e integram informações.",
        "reference": "`Neuroanatomia na prática.pdf` (p. 15), `Noções-de-neuroanatomia-e-neurofisiologia-Elisabete-Castelon-Konkiewitz-–-Neurociências-em-Debate.pdf` (p. 2), `Introducao_a_neuroanatomia_e_a_neurofisiologia.pdf` (p. 5)"
    },
    {
        "category": "Neurofisiologia",
        "question": "A principal função do neurônio é:",
        "options": [
            "Fornecer suporte físico ao tecido nervoso.",
            "Conduzir impulsos elétricos e químicos (sinais nervosos).",
            "Produzir líquido cefalorraquidiano.",
            "Defender o sistema nervoso contra patógenos."
        ],
        "correct_answer": "Conduzir impulsos elétricos e químicos (sinais nervosos).",
        "explanation": "Neurônios são as unidades funcionais do sistema nervoso, especializadas em transmitir informações através de sinais elétricos e químicos.",
        "reference": "`neuronios.pdf` (p. 8), `Noções-de-neuroanatomia-e-neurofisiologia-Elisabete-Castelon-Konkiewitz-–-Neurociências-em-Debate.pdf` (p. 1)"
    },
    # --- COLE AS OUTRAS 138 PERGUNTAS AQUI ---
    # Certifique-se de que cada pergunta é um dicionário e que eles estão separados por vírgulas.
    # Exemplo das últimas perguntas para completar o total:
    {
        "category": "Neuroanatomia",
        "question": "Qual é o nome da estrutura que separa os dois lobos parietais um do outro na linha média superior do cérebro?",
        "options": [
            "Sulco lateral.",
            "Fissura longitudinal.",
            "Sulco central.",
            "Sulco parieto-occipital."
        ],
        "correct_answer": "Fissura longitudinal.",
        "explanation": "A fissura longitudinal é a profunda invaginação que divide o cérebro em seus dois hemisférios (direito e esquerdo), consequentemente separando os lobos parietais um do outro na linha média superior.",
        "reference": "`Neuroanatomia na prática.pdf` (p. 16, figura 1.2)"
    },
    {
        "category": "Neurofisiologia",
        "question": "O que acontece com os canais de potássio dependentes de voltagem durante a fase de repolarização do potencial de ação?",
        "options": [
            "Eles se fecham rapidamente.",
            "Eles se abrem, permitindo o efluxo de K+ para fora da célula.",
            "Eles permitem o influxo de Na+.",
            "Eles são inativados."
        ],
        "correct_answer": "Eles se abrem, permitindo o efluxo de K+ para fora da célula.",
        "explanation": "Durante a repolarização, os canais de potássio dependentes de voltagem se abrem (lentamente), permitindo que os íons potássio saiam da célula. Isso faz com que o potencial de membrana retorne a valores negativos.",
        "reference": "`neuronios.pdf` (p. 29-30), `Introducao_a_neuroanatomia_e_a_neurofisiologia.pdf` (p. 4)"
    },
    {
        "category": "Neuroanatomia",
        "question": "Qual é a principal função dos corpos mamilares, que são parte do hipotálamo?",
        "options": [
            "Regulação da temperatura.",
            "Participação no circuito da memória e reconhecimento de memória.",
            "Controle da fome e da sede.",
            "Processamento de informações visuais."
        ],
        "correct_answer": "Participação no circuito da memória e reconhecimento de memória.",
        "explanation": "Os corpos mamilares, localizados na base do hipotálamo, são componentes importantes do circuito de Papez e estão envolvidos em processos de memória, especialmente na recuperação de memórias declarativas.",
        "reference": "`Neuroanatomia na prática.pdf` (p. 15, implicações funcionais)"
    },
    {
        "category": "Neuroanatomia",
        "question": "A Barreira Hematoencefálica (BHE) é uma estrutura crucial para proteger o SNC. Ela é formada principalmente por capilares com junções apertadas e processos dos:",
        "options": [
            "Micróglias.",
            "Oligodendrócitos.",
            "Astrócitos.",
            "Células de Schwann."
        ],
        "correct_answer": "Astrócitos.",
        "explanation": "Os astrócitos desempenham um papel fundamental na formação e manutenção da barreira hematoencefálica, que regula a passagem de substâncias do sangue para o tecido cerebral.",
        "reference": "`Introducao_a_neuroanatomia_e_a_neurofisiologia.pdf` (p. 2-3)"
    },
    {
        "category": "Neuroanatomia",
        "question": "Qual das seguintes estruturas NÃO faz parte do tronco encefálico?",
        "options": [
            "Mesencéfalo.",
            "Ponte.",
            "Tálamo.",
            "Bulbo."
        ],
        "correct_answer": "Tálamo.",
        "explanation": "O tronco encefálico é composto pelo mesencéfalo, ponte e bulbo. O tálamo faz parte do diencéfalo.",
        "reference": "`Neuroanatomia na prática.pdf` (p. 15), `Noções-de-neuroanatomia-e-neurofisiologia-Elisabete-Castelon-Konkiewitz-–-Neurociências-em-Debate.pdf` (p. 4)"
    },
    {
        "category": "Neuroanatomia",
        "question": "A área de Broca, crucial para a produção da fala e linguagem, está localizada em qual lobo cerebral?",
        "options": [
            "Lobo Temporal.",
            "Lobo Parietal.",
            "Lobo Frontal.",
            "Lobo Occipital."
        ],
        "correct_answer": "Lobo Frontal.",
        "explanation": "A área de Broca está classicamente localizada no lobo frontal do hemisfério dominante (geralmente o esquerdo) e é essencial para a produção da linguagem (fala e escrita).",
        "reference": "`Noções-de-neuroanatomia-e-neurofisiologia-Elisabete-Castelon-Konkiewitz-–-Neurociências-em-Debate.pdf` (p. 3), `Introducao_a_neuroanatomia_e_a_neurofisiologia.pdf` (p. 6)"
    },
    {
        "category": "Neuroanatomia",
        "question": "Qual é o nome da estrutura que é o ponto de decussação (cruzamento) dos nervos ópticos, onde parte das fibras de cada olho cruza para o lado oposto do cérebro?",
        "options": [
            "Tálamo.",
            "Colículo superior.",
            "Quiasma óptico.",
            "Corpo geniculado lateral."
        ],
        "correct_answer": "Quiasma óptico.",
        "explanation": "O quiasma óptico é o ponto na base do cérebro onde as fibras do nervo óptico de cada olho se cruzam parcialmente, garantindo que as informações do campo visual esquerdo de ambos os olhos vão para o lado direito do cérebro, e vice-versa.",
        "reference": "`Noções-de-neuroanatomia-e-neurofisiologia-Elisabete-Castelon-Konkiewitz-–-Neurociências-em-Debate.pdf` (p. 5)"
    }
]

# Separa as perguntas por categoria para uso inicial e recarga
_all_neuroanatomy_questions = [q for q in all_questions_raw if q["category"] == "Neuroanatomia"]
_all_neurophysiology_questions = [q for q in all_questions_raw if q["category"] == "Neurofisiologia"]

# Embaralha as listas uma única vez ao carregar o script
random.shuffle(_all_neuroanatomy_questions)
random.shuffle(_all_neurophysiology_questions)


# --- Configuração do Streamlit ---
st.set_page_config(layout="centered", page_title="Quiz de Neurociências")

st.title("🧠 Quiz Interativo de Neurociências")
st.markdown("Teste seus conhecimentos em Neuroanatomia e Neurofisiologia!")

# --- Inicialização de estados de sessão ---
if 'quiz_started' not in st.session_state:
    st.session_state.quiz_started = False
if 'current_question_index' not in st.session_state:
    st.session_state.current_question_index = 0
if 'score' not in st.session_state:
    st.session_state.score = 0
if 'selected_option' not in st.session_state:
    st.session_state.selected_option = None
if 'answered_correctly' not in st.session_state:
    st.session_state.answered_correctly = None
if 'show_explanation' not in st.session_state:
    st.session_state.show_explanation = False
if 'quiz_finished' not in st.session_state:
    st.session_state.quiz_finished = False
if 'filtered_questions' not in st.session_state:
    st.session_state.filtered_questions = []
if 'num_questions_per_category' not in st.session_state:
    st.session_state.num_questions_per_category = 5 # 5 perguntas por categoria

# Novos estados para gerenciar o índice atual de cada pool embaralhado
# Estes índices controlam de onde as próximas 5 perguntas serão tiradas.
if 'current_index_neuroanatomy' not in st.session_state:
    st.session_state.current_index_neuroanatomy = 0
if 'current_index_neurophysiology' not in st.session_state:
    st.session_state.current_index_neurophysiology = 0

# --- Funções do Quiz ---

def get_next_questions_from_pool(pool_name, num_questions_needed):
    """
    Pega um certo número de perguntas do pool especificado,
    avançando o índice e reembaralhando o pool se necessário.
    Retorna as perguntas selecionadas.
    """
    if pool_name == "Neuroanatomia":
        current_pool = _all_neuroanatomy_questions
        current_index_key = 'current_index_neuroanatomy'
    else: # Neurofisiologia
        current_pool = _all_neurophysiology_questions
        current_index_key = 'current_index_neurophysiology'

    start_index = st.session_state[current_index_key]
    end_index = start_index + num_questions_needed

    # Se o número de perguntas necessárias exceder o que resta no pool,
    # reinicializa o pool (reembaralha e reseta o índice)
    if end_index > len(current_pool):
        st.sidebar.warning(f"Reinicializando banco de perguntas de {pool_name} para novas sequências...")
        random.shuffle(current_pool) # Reembaralha o pool completo
        st.session_state[current_index_key] = 0 # Reseta o índice para o início
        start_index = 0 # Reinicia a contagem para esta seleção
        end_index = start_index + num_questions_needed

        # Se ainda assim o pool for muito pequeno (menos que o num_questions_needed)
        # pegamos o que sobrou. Isso não deve acontecer com 70 perguntas e 5 necessárias,
        # mas é uma garantia.
        if end_index > len(current_pool):
            end_index = len(current_pool)


    selected = current_pool[start_index:end_index]
    st.session_state[current_index_key] = end_index # Atualiza o índice para a próxima vez
    return selected

def start_quiz_callback(category_filter):
    """Callback para iniciar o quiz, filtrando e selecionando perguntas de forma não repetitiva."""

    selected_questions = []
    num_to_select_per_cat = st.session_state.num_questions_per_category

    if category_filter == "Todas":
        selected_questions.extend(get_next_questions_from_pool("Neuroanatomia", num_to_select_per_cat))
        selected_questions.extend(get_next_questions_from_pool("Neurofisiologia", num_to_select_per_cat))
        random.shuffle(selected_questions) # Embaralha o resultado final para misturar as categorias

    else: # Se uma categoria específica foi selecionada
        selected_questions.extend(get_next_questions_from_pool(category_filter, num_to_select_per_cat))
        random.shuffle(selected_questions) # Apenas embaralha

    st.session_state.filtered_questions = selected_questions
    st.session_state.quiz_started = True
    st.session_state.current_question_index = 0
    st.session_state.score = 0
    st.session_state.selected_option = None
    st.session_state.answered_correctly = None
    st.session_state.show_explanation = False
    st.session_state.quiz_finished = False

def next_question_callback():
    """Avança para a próxima pergunta."""
    st.session_state.current_question_index += 1
    st.session_state.selected_option = None
    st.session_state.answered_correctly = None
    st.session_state.show_explanation = False
    if st.session_state.current_question_index >= len(st.session_state.filtered_questions):
        st.session_state.quiz_finished = True

def restart_quiz_callback():
    """Reinicia o quiz."""
    st.session_state.quiz_started = False
    st.session_state.current_question_index = 0
    st.session_state.score = 0
    st.session_state.selected_option = None
    st.session_state.answered_correctly = None
    st.session_state.show_explanation = False
    st.session_state.quiz_finished = False
    st.session_state.filtered_questions = [] # Limpa as perguntas filtradas
    # Não zera os 'current_index_X' aqui, para que o próximo quiz pegue as próximas perguntas.


# --- Interface do Quiz ---

if not st.session_state.quiz_started:
    st.write("Escolha uma categoria para começar o quiz. Serão selecionadas 5 perguntas por categoria (se houver disponível).")
    categories = ["Todas", "Neuroanatomia", "Neurofisiologia"]
    selected_category = st.selectbox("Selecione a Categoria:", categories, key="category_select")

    if st.button("Iniciar Quiz", on_click=lambda: start_quiz_callback(selected_category)):
        pass
else:
    if st.session_state.quiz_finished:
        total_questions = len(st.session_state.filtered_questions)
        percentage_correct = (st.session_state.score / total_questions) * 100 if total_questions > 0 else 0
        st.success(f"Quiz Concluído! Sua pontuação final: {st.session_state.score} de {total_questions} ({percentage_correct:.2f}% de acerto)")

        # Botão Reiniciar Quiz
        if st.button("Reiniciar Quiz", on_click=restart_quiz_callback):
            pass
    else:
        current_question = st.session_state.filtered_questions[st.session_state.current_question_index]

        st.subheader(f"Pergunta {st.session_state.current_question_index + 1}/{len(st.session_state.filtered_questions)}")
        st.markdown(f"**Categoria:** {current_question['category']}")
        st.write(current_question["question"])

        selected_option_key = f"q_{st.session_state.current_question_index}_option"

        options_disabled = st.session_state.selected_option is not None

        user_choice = st.radio(
            "Escolha uma opção:",
            current_question["options"],
            key=selected_option_key,
            index=None,
            disabled=options_disabled
        )

        if user_choice and st.session_state.selected_option is None:
            st.session_state.selected_option = user_choice
            if user_choice == current_question["correct_answer"]:
                st.session_state.answered_correctly = True
                st.session_state.score += 1
            else:
                st.session_state.answered_correctly = False
            st.session_state.show_explanation = True

        if st.session_state.selected_option is not None:
            if st.session_state.answered_correctly:
                st.success("✅ Resposta Correta!")
            else:
                st.error("❌ Resposta Incorreta.")
                st.write(f"A resposta correta era: **{current_question['correct_answer']}**")

            if st.session_state.show_explanation:
                st.info(f"**Explicação:** {current_question['explanation']}")
                if current_question['reference']:
                    st.caption(f"**Referência:** {current_question['reference']}")

            st.write("")

            if st.button("Próxima Pergunta", on_click=next_question_callback):
                pass

        st.markdown(f"---")
        st.write(f"**Pontuação Atual:** {st.session_state.score} / {st.session_state.current_question_index + 1}")